#!/usr/bin/env bash
# Installs nginx server and a redirection endpoint

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/emmydev9 permanent;/" /etc/nginx/sites-available/default
service nginx start
